-- OUT_DIR and INT_DIR must be defined in the top-most premake file before including this file

include "physx/source/fastxml"
include "physx/source/lowlevel"
include "physx/source/lowlevelaabb"
include "physx/source/lowleveldynamics"
include "physx/pvdruntime"
include "physx/source/foundation"
include "physx/source/task"
include "physx/source/scenequery"
include "physx/source/simulationcontroller"
include "physx/source/physxcharacterkinematic"
include "physx/source/common"
include "physx/source/pvd"
include "physx/source/physxcooking"
include "physx/source/physx"
include "physx/source/physxextensions"
